-- MySQL Script generated by MySQL Workbench
-- Thu Aug 17 17:24:05 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema auction_site_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema auction_site_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `auction_site_db` ;
USE `auction_site_db` ;

-- -----------------------------------------------------
-- Table `auction_site_db`.`admin_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auction_site_db`.`admin_table` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `full_name` VARCHAR(150) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `username` VARCHAR(100) CHARACTER SET 'utf8mb3' NOT NULL,
  `password` VARCHAR(100) CHARACTER SET 'utf8mb3' NOT NULL,
  `email` VARCHAR(200) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 13;


-- -----------------------------------------------------
-- Table `auction_site_db`.`artinfo_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auction_site_db`.`artinfo_table` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) COLLATE 'utf8mb3_persian_ci' NOT NULL,
  `description` VARCHAR(500) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `photo_path` VARCHAR(500) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 12;


-- -----------------------------------------------------
-- Table `auction_site_db`.`auction_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auction_site_db`.`auction_table` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `art_id` INT NOT NULL,
  `admin_id` INT NOT NULL,
  `limit_price` VARCHAR(100) COLLATE 'utf8mb3_persian_ci' NOT NULL,
  `start_date` DATETIME NOT NULL,
  `end_date` DATETIME NOT NULL,
  `status` ENUM('0', '1') CHARACTER SET 'utf8mb3' NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_auction_table_1_idx` (`admin_id` ASC) VISIBLE,
  INDEX `fk_auction_table_2_idx` (`art_id` ASC) VISIBLE,
  CONSTRAINT `fk_auction_table_1`
    FOREIGN KEY (`admin_id`)
    REFERENCES `auction_site_db`.`admin_table` (`id`),
  CONSTRAINT `fk_auction_table_2`
    FOREIGN KEY (`art_id`)
    REFERENCES `auction_site_db`.`artinfo_table` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11;


-- -----------------------------------------------------
-- Table `auction_site_db`.`user_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auction_site_db`.`user_table` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fullname` VARCHAR(150) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `email` VARCHAR(200) CHARACTER SET 'utf8mb3' NOT NULL,
  `password` VARCHAR(100) CHARACTER SET 'utf8mb3' NOT NULL,
  `phone_number` VARCHAR(13) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `address` VARCHAR(500) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `id_card_code` VARCHAR(50) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `commitment_status` ENUM('0', '1') COLLATE 'utf8mb3_persian_ci' NOT NULL,
  `id_card_photo_path` VARCHAR(500) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `user_status` ENUM('0', '1') CHARACTER SET 'utf8mb3' NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `id_card_code_UNIQUE` (`id_card_code` ASC) VISIBLE,
  UNIQUE INDEX `phone_number_UNIQUE` (`phone_number` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 10;


-- -----------------------------------------------------
-- Table `auction_site_db`.`auction_participant_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auction_site_db`.`auction_participant_table` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `auction_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `perposed_price` VARCHAR(100) CHARACTER SET 'utf8mb3' NOT NULL,
  `perposed_datetime` DATETIME NOT NULL,
  `status_collateral` ENUM('0', '1') CHARACTER SET 'utf8mb3' NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_auction_participant_table_2_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_auction_participant_table_1_idx` (`auction_id` ASC) VISIBLE,
  CONSTRAINT `fk_auction_participant_table_1`
    FOREIGN KEY (`auction_id`)
    REFERENCES `auction_site_db`.`auction_table` (`id`),
  CONSTRAINT `fk_auction_participant_table_2`
    FOREIGN KEY (`user_id`)
    REFERENCES `auction_site_db`.`user_table` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4;


-- -----------------------------------------------------
-- Table `auction_site_db`.`contactus_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auction_site_db`.`contactus_table` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(200) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `tell_phone` VARCHAR(13) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `address` VARCHAR(500) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 2;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
