package Enum;

public enum StatusQuery {
    SUCCESS,
    FAILD,
    FAILD_DEPENDENCY,
    PARAMETER_NOT_VALID,
    RECORD_EXIST,
    SUCCESS_IMAGE_FAILD,
    PASSWORD_INCORRECT,
    NEW_PASSWORD_RETRY_INCORRECT,
    USERNAME_PASSWORD_INCORRECT,
    COMMITMENT_NOT_ACCEPT;
}
